import React from 'react';
import { Resource } from '../types';
import { ExternalLink, FileText, Code2, Youtube, Database, Box } from 'lucide-react';

const resources: Resource[] = [
  { id: '1', title: 'Base IEEE Paper (Abuhmed et al.)', url: '#', category: 'Paper' },
  { id: '2', title: 'Unity Traffic Visualization Asset', url: 'https://assetstore.unity.com/', category: 'Tool' },
  { id: '3', title: 'SUMO-RL GitHub Repository', url: 'https://github.com/LucasAlegre/sumo-rl', category: 'Code' },
  { id: '4', title: 'TraCI Python Interface Docs', url: 'https://sumo.dlr.de/docs/TraCI.html', category: 'Code' },
  { id: '5', title: 'SUMO2Unity Visualization', url: 'https://github.com/SimuTraffX-Lab/SUMO2Unity', category: 'Code' },
  { id: '6', title: 'Reinforcement Learning Data Analysis', url: '#', category: 'Tutorial' },
];

export const Resources: React.FC = () => {
  const getIcon = (category: string) => {
    switch (category) {
      case 'Paper': return <FileText className="text-purple-500" />;
      case 'Code': return <Code2 className="text-emerald-500" />;
      case 'Tutorial': return <Youtube className="text-red-500" />;
      case 'Tool': return <Box className="text-blue-500" />;
      default: return <ExternalLink className="text-blue-500" />;
    }
  };

  return (
    <div className="p-8 ml-64">
      <div className="mb-8">
        <h2 className="text-3xl font-bold text-slate-800">Project Resources</h2>
        <p className="text-slate-600 mt-2">Essential documentation, libraries, and reference papers.</p>
      </div>

      <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-6">
        {resources.map((res) => (
          <a 
            key={res.id} 
            href={res.url} 
            target="_blank" 
            rel="noreferrer"
            className="group block bg-white p-6 rounded-xl border border-slate-200 hover:border-emerald-400 hover:shadow-md transition-all"
          >
            <div className="flex justify-between items-start mb-4">
              <div className="p-3 bg-slate-50 rounded-lg group-hover:bg-emerald-50 transition-colors">
                {getIcon(res.category)}
              </div>
              <span className="text-xs font-bold text-slate-400 uppercase tracking-wider">{res.category}</span>
            </div>
            <h3 className="font-bold text-slate-800 mb-2 group-hover:text-emerald-600 transition-colors">{res.title}</h3>
            <p className="text-sm text-slate-500 flex items-center gap-1">
              Open Resource <ExternalLink size={12} />
            </p>
          </a>
        ))}
      </div>

      {/* Data Management Section */}
      <div className="mt-8 bg-white rounded-xl shadow-sm border border-slate-200 p-8">
        <div className="flex items-center gap-3 mb-6">
          <div className="p-2 bg-blue-100 rounded-lg">
            <Database className="text-blue-600" size={24} />
          </div>
          <div>
             <h3 className="text-xl font-bold text-slate-800">Where is the Data?</h3>
             <p className="text-sm text-slate-500">Understanding Data Flow in Reinforcement Learning</p>
          </div>
        </div>
        
        <div className="grid grid-cols-1 md:grid-cols-2 gap-8">
          <div className="space-y-3">
             <h4 className="font-bold text-slate-700 border-b border-slate-100 pb-2">Training Data (Input)</h4>
             <p className="text-sm text-slate-600 leading-relaxed">
               In RL, we do not have a static dataset. The "Training Data" is the <strong>Configuration</strong> of the simulation.
             </p>
             <ul className="list-disc list-inside text-sm text-slate-600 space-y-1">
               <li><strong>Map:</strong> <code>klong_toei.net.xml</code> (The physical world)</li>
               <li><strong>Demand:</strong> <code>traffic.rou.xml</code> (The vehicle generation rates)</li>
               <li><strong>State:</strong> Real-time Queue Lengths (Generated by SUMO)</li>
             </ul>
          </div>

          <div className="space-y-3">
             <h4 className="font-bold text-slate-700 border-b border-slate-100 pb-2">Testing Data (Output)</h4>
             <p className="text-sm text-slate-600 leading-relaxed">
               The "Testing Data" is the <strong>Log Files</strong> generated when running the trained model against the environment.
             </p>
             <ul className="list-disc list-inside text-sm text-slate-600 space-y-1">
               <li><strong>CSV Logs:</strong> <code>test_results.csv</code> (Run <code>test.py</code> to generate)</li>
               <li><strong>Metrics:</strong> Average Waiting Time, Total Throughput, CO2 Emissions.</li>
               <li><strong>Visual:</strong> Unity Recording of the traffic flow.</li>
             </ul>
          </div>
        </div>
      </div>

      <div className="mt-8 bg-indigo-900 rounded-2xl p-8 text-white relative overflow-hidden">
        <div className="absolute top-0 right-0 w-64 h-64 bg-indigo-800 rounded-full mix-blend-multiply filter blur-3xl opacity-50 transform translate-x-1/2 -translate-y-1/2"></div>
        <div className="relative z-10">
          <h3 className="text-2xl font-bold mb-4">Unity Integration Tip</h3>
          <p className="text-indigo-200 max-w-2xl mb-6">
             When connecting Unity to Python, ensure your <strong>Firewall</strong> allows TCP connections on Port 4042. 
             If objects aren't moving in Unity, check that the vehicle IDs in SUMO match the Prefab names in Unity.
          </p>
          <div className="inline-block bg-indigo-800 px-4 py-2 rounded-lg font-mono text-sm border border-indigo-700">
            Protocol: TCP/IP JSON Serialization
          </div>
        </div>
      </div>
    </div>
  );
};